name: Update Meals Gist

on:
  schedule:
    - cron: "5 */12 * * *"
  workflow_dispatch:

permissions:
  contents: read
  gists: write

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate meals data
        env:
          ICAL_URL: ${{ secrets.ICAL_URL }}
        run: python app.py

      - name: Create/Update Gist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_ID: ${{ vars.GIST_ID }}
        run: |
          CONTENT=$(cat meals.json | jq -c . | jq -R .)

          if [ -n "$GIST_ID" ]; then
            # Update existing gist
            curl -X PATCH \
              -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/gists/$GIST_ID" \
              -d "{\"files\":{\"meals.json\":{\"content\":$CONTENT}}}"
          else
            # Create new gist
            RESPONSE=$(curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/gists" \
              -d "{\"public\":true,\"files\":{\"meals.json\":{\"content\":$CONTENT}}}")
            
            echo "New Gist ID: $(echo "$RESPONSE" | jq -r .id)"
            echo "Raw URL: $(echo "$RESPONSE" | jq -r '.files."meals.json".raw_url')"
          fi
