name: Update Meals

on:
  schedule:
    # Run every 12 hours at 5 minutes past the hour
    - cron: "5 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-meals:
    runs-on: ubuntu-latest

    # Option A: set env for the whole job (every step gets it)
    env:
      ICAL_URL: ${{ secrets.ICAL_URL }}
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional masked sanity check (won't print the token)
      - name: Verify env presence (masked)
        run: |
          python - <<'PY'
          import os, sys
          assert os.getenv("GIST_TOKEN"), "GIST_TOKEN missing"
          assert os.getenv("ICAL_URL"), "ICAL_URL missing"
          print("Env looks good ✅")
          PY

      - name: Run meal planning script
        run: python app.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add meals.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update meals.json"
          git push
