name: Update Meals

on:
  schedule:
    # Run every 12 hours at 5 minutes past the hour
    - cron: "5 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-meals:
    runs-on: ubuntu-latest

    env:
      ICAL_URL: ${{ secrets.ICAL_URL }}
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      GIST_ID: ${{ secrets.GIST_ID }} # optional

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run meal planning script
        run: python app.py

      - name: Commit and push changes (skip if no file)
        run: |
          FILE_PATH="meals.json"
          if [ ! -f "$FILE_PATH" ]; then
            echo "No $FILE_PATH found. Skipping commit."
            exit 0
          fi
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "$FILE_PATH"
          git diff --cached --quiet && { echo "No changes to commit."; exit 0; }
          git commit -m "Update meals.json"
          git push
