name: Update Meals

on:
  schedule:
    - cron: "5 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-meals:
    runs-on: ubuntu-latest

    env:
      ICAL_URL: ${{ secrets.ICAL_URL }}
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      GIST_ID: ${{ secrets.GIST_ID }} # the hex id from https://gist.github.com/<user>/<id>

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Verify that the token can access the gist BEFORE running your script
      - name: Verify Gist access
        run: |
          set -euo pipefail
          test -n "${GIST_ID}" || { echo "GIST_ID is empty"; exit 1; }
          # Try GET the gist metadata
          code=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${GIST_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/gists/${GIST_ID}")
          if [ "$code" != "200" ]; then
            echo "Failed to access gist ${GIST_ID}. HTTP $code"
            echo "Likely causes: bad GIST_ID, token not from gist owner, or token lacks gist:write"
            exit 1
          fi
          echo "Gist access OK."

      - name: Run meal planning script
        run: python app.py
